const CONST_UNKNOWN_LABEL: string = "Unknown";
const CONST_AUTO_ATTACK_ID: number = 0;
const CONST_AUTO_ATTACK_LABEL: string = "Auto Attack";
const CONST_UNKNOWN_ABILITY_ID: number = 2;

export {CONST_UNKNOWN_LABEL, CONST_AUTO_ATTACK_ID, CONST_AUTO_ATTACK_LABEL, CONST_UNKNOWN_ABILITY_ID};
