FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm rustup gcc cmake openssl pkgconf
RUN rustup toolchain install nightly
RUN rustup default nightly

COPY ./cleanup.sh ./
RUN chmod +x ./cleanup.sh

RUN ./cleanup.sh
ADD ./Backend ./Backend
RUN chmod -R 777 ./Backend
COPY start.sh ./

CMD ["/usr/bin/bash", "./start.sh"]