pub enum MessageType {
  MeleeDamage = 0,
  SpellDamage = 1,
  Heal = 2,
  Death = 3,
  AuraApplication = 4,
  Dispel = 5,
  SpellSteal = 6,
  Interrupt = 7,
  Position = 8,
  CombatState = 9,
  Power = 10,
  Loot = 11,
  SpellCast = 12,
  Threat = 13,
  Event = 14,
  Summon = 15,
  InstancePvPStart = 16,
  InstancePvPEndUnratedArena = 17,
  InstancePvPEndRatedArena = 18,
  InstancePvPEndBattleground = 19
}