FROM archlinux:latest

RUN pacman -Sy --noconfirm
RUN pacman -S --noconfirm git openssl pkgconf docker docker-compose

COPY ./Services ./
COPY ./configuration.sh ./
RUN git clone --single-branch --branch dev https://github.com/Geigerkind/LegacyPlayersV3
RUN chmod -R 777 ./LegacyPlayersV3/Exporter
RUN cp -r ./LegacyPlayersV3/Exporter/Database ./lp_cm_mariadb/
RUN cp -r ./LegacyPlayersV3/Exporter/Backend ./lp_cm_backend/ && cp ./configuration.sh ./lp_cm_backend/
RUN cp -r ./LegacyPlayersV3/Exporter/Webclient ./lp_cm_webclient/

COPY ./start.sh ./
CMD ["/usr/bin/bash", "./start.sh"]