FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm git openssl pkgconf docker docker-compose

COPY ./Services ./
RUN git clone https://github.com/Geigerkind/LegacyPlayersV3
RUN chmod -R 777 ./LegacyPlayersV3/Exporter
RUN cp -r ./LegacyPlayersV3/Exporter/Database ./lp_cm_mariadb/
RUN cp -r ./LegacyPlayersV3/Exporter/Backend ./lp_cm_backend/
RUN cp -r ./LegacyPlayersV3/Exporter/Webclient ./lp_cm_webclient/

COPY ./start.sh ./
CMD ["/usr/bin/bash", "./start.sh"]