export enum HitType {
    None = "None",
    OffHand = "OffHand",
    Evade = "Evade",
    Miss = "Miss",
    Dodge = "Dodge",
    PartialBlock = "PartialBlock",
    FullBlock = "FullBlock",
    Parry = "Parry",
    Glancing = "Glancing",
    Crit = "Crit",
    Crushing = "Crushing",
    Hit = "Hit",
    PartialResist = "PartialResist",
    FullResist = "FullResist",
    Immune = "Immune",
    Environment = "Environment",
    PartialAbsorb = "PartialAbsorb",
    FullAbsorb = "FullAbsorb",
    Interrupt = "Interrupt",
    Deflect = "Deflect",
    Split = "Split",
    Reflect = "Reflect"
}
