FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm rustup gcc cmake openssl pkgconf zeromq
RUN rustup toolchain install nightly
RUN rustup default nightly

WORKDIR /Backend

ENV RUST_ENV=production

CMD ["cargo", "run", "--release"]